### ISSUE TITLE
Provide credit

### ISSUE THREAD

**Issue by jbarson** [Skwiggums/Lego-Studio-Stuff#1]
Love these plans, very inspiring.

You have a couple of essays by Ken Burnside in you inspiration folder.  Rather than share them, can you instead point to where you can purchase these?

https://www.adastragames.com/products/conditionzulu
https://www.adastragames.com/products/the-hot-equations

You may also want to include the third essay in the series:

https://www.adastragames.com/products/objects-in-motion-orbital-mechanics-for-writers

**Comment by Skwiggums** [comment]
Done, removed the files for the docs and put some blurbs gushing about hot equations and condition zulu in the accreditation doc.
